
name: lifeease
description: Accessible reminder and assistance app for elderly and child users.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.3.1
  flutter_tts: ^4.0.2
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  intl: ^0.19.0
  path: ^1.9.0
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  sizer: ^2.0.15
  speech_to_text: ^7.0.0
  supabase_flutter: ^2.8.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - env.json
    - assets/images/logo.png
    - assets/images/avatar.png
    - assets/images/no-image.jpg
    - assets/images/sad_face.svg

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo.png
  android: true
  ios: false
  web: false
